# name: Deploy Landing Page & Docs

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types:
#       - opened
#       - synchronize

# permissions:
#   contents: write
#   pull-requests: write
#   pages: write

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
#         with:
#           submodules: true

#       - name: Setup mdBook
#         run: cargo install mdbook

#       - name: Build mdBook docs
#         run: mdbook build docs

#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: gh-pages
#           folder: .


name: Deploy Landing Page

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: git submodule update --remote --merge

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
